//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.0+e52e987
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Home Page</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel, IContactProperties, IDisclosure, IExploreProperties, IFooterCopyRight, IHeaderProperties, INavBarProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HomePage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Card  Features
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardFeatures")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel CardFeatures => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "cardFeatures");

		///<summary>
		/// Carousel Features
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("carouselFeatures")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel CarouselFeatures => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "carouselFeatures");

		///<summary>
		/// MiniCarousel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("miniCarousel")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MiniCarousel => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "miniCarousel");

		///<summary>
		/// isVisible
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("isVisible")]
		public virtual bool IsVisible => global::Umbraco.Cms.Web.Common.PublishedModels.ContactProperties.GetIsVisible(this, _publishedValueFallback);

		///<summary>
		/// Texto: Enter a text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("texto")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Texto => global::Umbraco.Cms.Web.Common.PublishedModels.ContactProperties.GetTexto(this, _publishedValueFallback);

		///<summary>
		/// isVisibleDisclosure
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("isVisibleDisclosure")]
		public virtual bool IsVisibleDisclosure => global::Umbraco.Cms.Web.Common.PublishedModels.Disclosure.GetIsVisibleDisclosure(this, _publishedValueFallback);

		///<summary>
		/// Texto Disclosure
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("textoDisclosure")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString TextoDisclosure => global::Umbraco.Cms.Web.Common.PublishedModels.Disclosure.GetTextoDisclosure(this, _publishedValueFallback);

		///<summary>
		/// isVisibleExplore
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("isVisibleExplore")]
		public virtual bool IsVisibleExplore => global::Umbraco.Cms.Web.Common.PublishedModels.ExploreProperties.GetIsVisibleExplore(this, _publishedValueFallback);

		///<summary>
		/// Nombre Botones
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nombreBotones")]
		public virtual global::System.Collections.Generic.IEnumerable<string> NombreBotones => global::Umbraco.Cms.Web.Common.PublishedModels.ExploreProperties.GetNombreBotones(this, _publishedValueFallback);

		///<summary>
		/// Titulo Seccion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tituloSeccion")]
		public virtual string TituloSeccion => global::Umbraco.Cms.Web.Common.PublishedModels.ExploreProperties.GetTituloSeccion(this, _publishedValueFallback);

		///<summary>
		/// CopyRight Footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("copyRightFooter")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString CopyRightFooter => global::Umbraco.Cms.Web.Common.PublishedModels.FooterCopyRight.GetCopyRightFooter(this, _publishedValueFallback);

		///<summary>
		/// Quick links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("quickLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<string> QuickLinks => global::Umbraco.Cms.Web.Common.PublishedModels.FooterCopyRight.GetQuickLinks(this, _publishedValueFallback);

		///<summary>
		/// Secciones Politica Footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seccionesPoliticaFooter")]
		public virtual global::System.Collections.Generic.IEnumerable<string> SeccionesPoliticaFooter => global::Umbraco.Cms.Web.Common.PublishedModels.FooterCopyRight.GetSeccionesPoliticaFooter(this, _publishedValueFallback);

		///<summary>
		/// SocialMedia
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("socialMedia")]
		public virtual global::System.Collections.Generic.IEnumerable<string> SocialMedia => global::Umbraco.Cms.Web.Common.PublishedModels.FooterCopyRight.GetSocialMedia(this, _publishedValueFallback);

		///<summary>
		/// Title: Enter a title for this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Logo => global::Umbraco.Cms.Web.Common.PublishedModels.NavBarProperties.GetLogo(this, _publishedValueFallback);

		///<summary>
		/// Menu Navegacion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuNavegacion")]
		public virtual global::System.Collections.Generic.IEnumerable<string> MenuNavegacion => global::Umbraco.Cms.Web.Common.PublishedModels.NavBarProperties.GetMenuNavegacion(this, _publishedValueFallback);

		///<summary>
		/// User Login
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("userLogin")]
		public virtual bool UserLogin => global::Umbraco.Cms.Web.Common.PublishedModels.NavBarProperties.GetUserLogin(this, _publishedValueFallback);
	}
}
